Notebook created: 2018-01-04 10:10:22  
Generated from: _build_jl/jl/julia_by_example.rst  

In [ ]:
using Plots
ts_length = 100
epsilon_values = randn(ts_length)
plot(epsilon_values, color="blue")

In [ ]:
typeof(epsilon_values)

```none
Array{Float64,1}
```


In [ ]:
epsilon_values

```none
100-element Array{Float64,1}:
 -0.16706
 -0.44692
  0.0131702
  0.187735
 -1.84894
  0.729719
 -1.62587
  0.518996
 -0.723798
  0.00738428
 -0.394932
  0.0825062
  1.81214
  ⋮
  0.148999
  0.0376599
  1.20136
  1.47377
  0.951305
  0.100777
  0.189895
  0.883207
  1.21965
 -1.35306
 -1.14473
  0.527658
```


In [ ]:
x = [10, "foo", false]

```none
3-element Array{Any,1}:
    10
      "foo"
 false
```


In [ ]:
typeof(x[1])

```none
Int64
```


In [ ]:
typeof(x[2])

```none
String
```


In [ ]:
typeof(x[3])

```none
Bool
```


In [ ]:
length(x)

```none
3
```


In [ ]:
pop!(x)

```none
false
```


In [ ]:
x

```none
2-element Array{Any,1}:
 10
   "foo"
```


In [ ]:
push!(x, "bar")

```none
3-element Array{Any,1}:
 10
   "foo"
   "bar"
```


In [ ]:
x

```none
3-element Array{Any,1}:
 10
   "foo"
   "bar"
```


In [ ]:
ts_length = 100
epsilon_values = Array{Float64}(ts_length)
for i in 1:ts_length
    epsilon_values[i] = randn()
end
plot(epsilon_values, color="blue")

In [ ]:
words = ["foo", "bar"]
for word in words
    println("Hello $word")
end

```none
Hello foo
Hello bar
```


In [ ]:
ts_length = 100
epsilon_values = Array{Float64}(ts_length)
i = 1
while i <= ts_length
    epsilon_values[i] = randn()
    i = i + 1
end
plot(epsilon_values, color="blue")

In [ ]:
ts_length = 100
epsilon_values = Array{Float64}(ts_length)
i = 1
while true
    epsilon_values[i] = randn()
    i = i + 1
    if i > ts_length
        break
    end
end
plot(epsilon_values, color="blue")

In [ ]:
function generate_data(n)
    epsilon_values = Array{Float64}(n)
    for i = 1:n
        epsilon_values[i] = randn()
    end
    return epsilon_values
end

ts_length = 100
data = generate_data(ts_length)
plot(data, color="blue")

In [ ]:
ts_length = 100
data = randn(ts_length)
plot(data, color="blue")

In [ ]:
Pkg.add("Distributions")

In [ ]:
using Distributions

function plot_histogram(distribution, n)
    epsilon_values = rand(distribution, n)  # n draws from distribution
    histogram(epsilon_values)
end

lp = Laplace()
plot_histogram(lp, 500)

In [ ]:
rand(3)

```none
3-element Array{Float64,1}:
 0.282284
 0.701812
 0.512708
```


In [ ]:
function factorial2(n)
    k = 1
    for i in 1:n
        k = k * i
    end
    return k
end

factorial2(4)

```none
24
```


In [ ]:
factorial(4)  # Built-in function

```none
24
```


In [ ]:
function binomial_rv(n, p)
    count = 0
    U = rand(n)
    for i in 1:n
        if U[i] < p
            count = count + 1    # Or count += 1
        end
    end
    return count
end

for j in 1:25
    b = binomial_rv(10, 0.5)
    print("$b, ")
end

```none
7, 4, 4, 3, 7, 5, 5, 6, 8, 5, 4, 4, 6, 8, 6, 6, 6, 5, 6, 7, 5, 6, 5, 2, 2,
```


In [ ]:
n = 1000000

count = 0
for i in 1:n
    u, v = rand(2)
    d = sqrt((u - 0.5)^2 + (v - 0.5)^2)  # Distance from middle of square
    if d < 0.5
        count += 1
    end
end

area_estimate = count / n

print(area_estimate * 4)  # dividing by radius**2

```none
3.139596
```


In [ ]:
payoff = 0
count = 0

print("Count = ")

for i in 1:10
    U = rand()
    if U < 0.5
        count += 1
    else
        count = 0
    end
    print(count)
    if count == 3
        payoff = 1
    end
end
print("\n")
println("payoff = $payoff")

```none
Count = 1010010120
payoff = 0
```


In [ ]:
a = 1 < 2 ? "foo" : "bar"
a

```none
"foo"
```


In [ ]:
a = 1 > 2 ? "foo" : "bar"
a

```none
"bar"
```


In [ ]:
payoff = 0
count = 0

print("Count = ")

for i in 1:10
    U = rand()
    count = U < 0.5 ? count + 1 : 0
    print(count)
    if count == 3
        payoff = 1
    end
end
print("\n")
println("payoff = $payoff")

```none
Count = 0010101230
payoff = 1
```


In [ ]:
alpha = 0.9
T = 200
x = zeros(T + 1)

for t in 1:T
    x[t+1] = alpha * x[t] + randn()
end
plot(x, color="blue")

In [ ]:
alphas = [0.0, 0.8, 0.98]
T = 200

series = []
labels = []

for alpha in alphas
    x = zeros(T + 1)
    x[1] = 0
    for t in 1:T
        x[t+1] = alpha * x[t] + randn()
    end
    push!(series, x)
    push!(labels, "alpha = $alpha")
end

plot(series, label=reshape(labels, 1, length(labels)))